### ISSUE TITLE
Can’t use CitadelCore behind a proxy

### ISSUE THREAD

**Issue by hitgubmitt** [TechnikEmpire/CitadelCore.Windows#17]
I am testing CitadelCore and it works great. However, I found that it can’t filter traffic when system is connected to another proxy. I tried SSH tunneling (ssh -D port user@ip) and squid web proxy. Neither worked.

Is this a known limitation? What is the cause of it?

**Comment by TechnikEmpire** [comment]
Ah I see, so you probably have the system proxy set and when its intercepting the connections they're CONNECT requests. That's my assumption.

CitadelCore.Windows has an option and function built into the packet diverter exclusively to detect SOCKS 4/5 proxies and drop their connections because no, CitadelCore does not work when another proxy is fighting to be the system proxy.

In fact without this enforced, things like Tor Browser and such can bypass Citadel altogether.

I have tested citadel behind vpns and such, and it does work, but just their nature, one proxy (especially with HTTPS enabled) will not work behind another, at least not without coding things explicitly around that purpose.

When HTTPS proxying happens, basically the proxy is to establish an opaque TCP pipe and just spin reading and writing until EOF. That's an unsupported use case. CitadelCore is designed to be the sole system proxy.

**Comment by TechnikEmpire** [comment]
Actually one thing you could do is:

1) Get the system proxy settings, namely the port number.
2) In the FirewallCallback, if the port matches the configured proxy port, choose to intercept.
3) See if Asp.NET Core actually handles the CONNECT. I'm not sure if it does.
