### ISSUE TITLE
What files are actually needed to run?

### ISSUE THREAD

**Issue by skxprive** [TechnikEmpire/CitadelCore.Windows#18]
Hi there,

Thanks for your project.
It runs fine when building, but I'm not sure what dlls are needed. When moving the executable+windivert dlls, it isn't working any more.

The build folder has like 50 Micoroft.net framework files.

**Comment by TechnikEmpire** [comment]
Asp.net core is a monolithic project, which this project uses internally for the proxy. It also depends heavily on whether you're using .net full or .net core.

You can try to trim down deps by doing ExcludeAssets=All in your csproj but there's not much that can be done to significantly reduce the number of assemblies.

**Comment by TechnikEmpire** [comment]
For greater clarity, as with most projects, all files that wind up in the build dir are needed. If you have a more specific error please let me know.

**Comment by skxprive** [comment]
Thanks

Does that mean the end-user doesn't require .net framework at all, but just require whatever is in the release folder? 
The release folder seem to have all the .net framework files as well such as System.Linq.dll.

**Comment by TechnikEmpire** [comment]
That will only be true if you publish as .net core with the self contained option.

Absent of that, What you're seeing is the mess caused by Microsoft with .net standard, .net core and .net full blending.

**Comment by skxprive** [comment]
That's a mess indeed. Msft *sigh*

1. So, i do know c++ do you recommend going with your discontinued project
and it basically works and just has 1 extra dll (.net core I assume)?

And

2. Can you point me in the right direction of what to do if we continue
with the c# option? As I think the end user still requires .net frameworks
to be installed even when distributing all the dlls that are in the build
folder.
C# code looks very clean btw. Well done

Op di 31 mrt. 2020 23:42 schreef Jesse Nicholson <notifications@github.com>:

**Comment by TechnikEmpire** [comment]
Thanks.

What I'm doing personally is I'm using .net core and I'm bundling the whole trimmed runtime in with my app.

I would not recommend using the c++ engine. IIRC, there was a memory leak in there and also its just not complete. This stuff is insanely complex and the scope is vast. That's why I jumped on the Microsoft train because it can be their burden to get HTTP right and maintain it, while I just focus on the product around that.

Like even with all their vast resources they're still running into problems all the time. Their HPACK implementation for example is broken. Maintaining working http code (engine code) is at least a full time job.

The managed portion of that project will incur the same issue. You'll need the .net runtime. So theres that as well.

Get on .net core full and Google the self contained and publish trimmed features. My own app installer is ~130 megs and its standalone.
